### ISSUE TITLE
undefined method `render_erb' for RackStep::Controller::ErbRendering:Module

### ISSUE THREAD

**Issue by tablecell** [mfdavid/rackstep#16]
```
class TimeController < RackStep::Controller
  def process_request
    time_hash = {:time => Time.now}
 
    response.content_type = "text/html"   
 
    ErbRendering::render_erb  "test"
  end
end

```

**Comment by marciofrayze** [comment]
These files contains an example that might help you: 
https://github.com/marciofrayze/rackstep/blob/master/test/util/sample_app.rb (search for SimpleErbPage)
https://github.com/marciofrayze/rackstep/blob/master/test/util/pages/justatesttemplate.erb

```
class SimpleErbPage < RackStep::Controller

  include RackStep::Controller::ErbRendering

  # Let's render an ERB template to test the RackStep::ErbRendering module.
  def process_request
    # Overwriting default directory (don't wanna create the whole default
    # folders structure).
    erb_templates_directory = 'test/util/pages'

    # Every attribute should be available for the template. In our case, it is
    # expecting to find the following attribute:
    @templateAttributeTest = 'This is the content of the attribute.'

    # Rendering the template.
    response.body = render_erb('justatesttemplate', erb_templates_directory)

    # Setting this request content type as html.
    response.content_type = 'text/html'
  end
end
```

The `render_erb` method contains an optional second parameter called `erb_template_directory` and it's default value is  `app/public/pages`. This method is defined at: https://github.com/marciofrayze/rackstep/blob/master/lib/controller.rb

I hope that might help you. If you still get stuck please let me know and I'll try to help more.

**Comment by tablecell** [comment]
` include RackStep::Controller::ErbRendering `  sovled problem.
 Thanks for your  support .
